spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: h2setting
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  output:
    ansi:
      enabled: always
logging.level:
  org.hibernate.SQL: debug
logging:
  file:
    name: /logs/logText.log