spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  profiles:
    active: ${profile}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  output:
    ansi:
      enabled: always
logging.level:
  org.hibernate.SQL: debug
logging:
  file:
    name: /logs/logText.log