spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: h2setting
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging.level:
  org.hibernate.SQL: debug